#!/bin/bash

# Create the irb configuration file
mkdir -p "${HOME}"
cat > "${HOME}/.irbrc" << EOF
require 'awesome_print'
AwesomePrint.irb!
IRB.conf[:SAVE_HISTORY] = 1000
IRB.conf[:HISTORY_FILE] = "#{ENV['HOME']}/.irb-history"
EOF

# Prepare the bundle config if BUNDLE_PATH is provided in order to avoid
# inconsistencies with how the bundler path is used
BUNDLE_CONFIG_FILE=".bundle/config"
read -r -d '' BUNDLE_CONFIG << EOF
---
BUNDLE_PATH: '${BUNDLE_PATH}'
EOF
if ! [ -f "${BUNDLE_CONFIG_FILE}" ] || [ "`< ${BUNDLE_CONFIG_FILE}`" != "${BUNDLE_CONFIG}" ]; then
  mkdir -p `dirname "${BUNDLE_CONFIG_FILE}"`
  echo "${BUNDLE_CONFIG}" > "${BUNDLE_CONFIG_FILE}"
fi

# Prepare the psql history file
mkdir -p `dirname "${PSQL_HISTORY}"`
touch "${PSQL_HISTORY}"

# Create a symlink for the log directory
mkdir -p /var/log/rails
rm -rf log
ln -nfs /var/log/rails log

# Create a symlink for the tmp directory
mkdir -p /tmp/rails
rm -rf tmp
ln -nfs /tmp/rails tmp

# Create a symlink for the public uploads directory
mkdir -p /var/lib/rails/uploads
rm -rf public/uploads
ln -nfs /var/lib/rails/uploads public/uploads

exec "$@"
